[global.limits]
forms = 1024000 # 1MB

[development]
address = "0.0.0.0"
port = 8000
workers = 2
keep_alive = 5
log = "normal"

[production]
address = "0.0.0.0"
port = 8000
keep_alive = 5
log = "critical"